### ISSUE TITLE
Some problem with the CLI

### ISSUE THREAD

**Issue by scorsi** [mcchatman8009/antlr4-tool#1]
Hello,

As I don't like to carry the antlr4 jar file into my repository, I was looking for a CLI to build my grammar.
I encountered some problem with the CLI.

### No arguments passed
When we type `npx antlr4-tool`, we got the following output:
```
Cannot read property 'join' of undefined
```
We should got option `-h` by default I guess.

### JavaScript language
It's a nice solution to give `antlr4.js`, maybe you should precise in the doc that it automatically output in JavaScript ? But it add complexity to the package. For me, it is unnecessary.
Maybe you could add some shortcut for the `JavaScript` language like `javascript` or `js`. I could imagine that for `TypeScript`, it is the same ?
I will create a pull request for this.

### More options ?
I would like to specify `-listener` or `-no-listener` and `-visitor` or `-no-visitor`.

### The "path" argument must be of type string. Received type object
Yeah, it is the really error. I typed the following command:
`antlr4-tool -l JavaScript -o src ./grammar/IDA.g4`
And I got the following error:
```
$ antlr4-tool -l JavaScript -o src ./grammar/IDA.g4
Compiling ./grammar/IDA.g4...
path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^


TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1090:7)
    at _.each (/Users/scorsi/Code/ida/node_modules/antlr4-tool/dist/antlr-core/index.js:11:33)
    at arrayEach (/Users/scorsi/Code/ida/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/Users/scorsi/Code/ida/node_modules/lodash/lodash.js:9342:14)
    at compileWithFunction (/Users/scorsi/Code/ida/node_modules/antlr4-tool/dist/antlr-core/index.js:9:7)
    at compileGrammarAsJavaScript (/Users/scorsi/Code/ida/node_modules/antlr4-tool/dist/antlr-core/index.js:39:12)
    at Object.compile (/Users/scorsi/Code/ida/node_modules/antlr4-tool/dist/antlr-core/index.js:53:20)
    at module.exports (/Users/scorsi/Code/ida/node_modules/antlr4-tool/dist/compile.js:9:34)
    at Object.<anonymous> (/Users/scorsi/Code/ida/node_modules/antlr4-tool/dist/cli.js:34:28)
```

Hope you could help

**Comment by mcchatman8009** [comment]
Thanks for reporting the issue. I’ll look into your issues and suggestions as soon.

**Comment by mcchatman8009** [comment]
I've published some fixes that hopefully address the issues you've outlined @scorsi. Please let me know if you have any more issues or problems. Thanks for all of your help.

**Comment by mcchatman8009** [comment]
Version 1.0.11 address these issues.

https://www.npmjs.com/package/antlr4-tool
