### ISSUE TITLE
Cannot find module 'antlr4/index'

### ISSUE THREAD

**Issue by Patrick-Remy** [mcchatman8009/antlr4-tool#14]
If I try to use the lib to compile a grammar outside of the source folder (e.g. on the Desktop), I'm receiving the following exception:

```
{ Error: Cannot find module 'antlr4/index'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._resolveFilename (…/node_modules/tsconfig-paths/lib/register.js:73:40)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at sandbox.require.id (…/node_modules/node-eval/index.js:61:48)
    ***at Object.<anonymous> (…/Desktop/eval.js:3:14)*** 
    at _commonjsEval (…/node_modules/node-eval/index.js:80:21)
    at module.exports (…/node_modules/node-eval/index.js:36:19)
    at Object.readParser (…/node_modules/antlr4-tool/src/antlr-core/parser-util.ts:20:20)
    at AntlrCompiler.compileTypeScript (…/node_modules/antlr4-tool/src/antlr-core/antlr-compiler.ts:83:37)
    at …/node_modules/antlr4-tool/src/antlr-core/index.ts:48:63
    at …/node_modules/antlr4-tool/src/antlr-core/index.ts:20:25
    at arrayEach (…/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (…/node_modules/lodash/lodash.js:9344:14)
    at compileWithFunction (…/node_modules/antlr4-tool/src/antlr-core/index.ts:10:7)
    at compileGrammarAsTypeScript (…/node_modules/antlr4-tool/src/antlr-core/index.ts:48:12)
```

**Comment by mcchatman8009** [comment]
@Patrick-Remy Yes, I have some thoughts on how to fix this issue. In my version two release, I planned on fixing this contextual problem. It would be ideal that the directory structure doesn't matter at all. 

As I'm sure that you're aware of, this is due to my attempt to load the parser temporarily, at runtime. 
I have some better and more elegant ways of handling this issue, without the need of the parser at runtime.

If your solution holds, then we'll go with that vmContext approach in the version 1 release to come. 

Thanks
