### ISSUE TITLE
Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by scorsi** [mcchatman8009/antlr4-tool#3]
Hello again,

When we use the antlr4-tool cli without argument, it crashes. Generally, the help is shown by default.

```
MBP-de-Sylvain:ida scorsi$ antlr4-tool 
/Users/scorsi/.config/yarn/global/node_modules/antlr4-tool/dist/cli.js:32
    log(`Compiling ${antlrGrammars.join(', ')}...`);
                                   ^

TypeError: Cannot read property 'join' of undefined
    at Object.<anonymous> (/Users/scorsi/.config/yarn/global/node_modules/antlr4-tool/dist/cli.js:32:36)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/scorsi/.config/yarn/global/node_modules/antlr4-tool/dist/app.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
```

**Comment by scorsi** [comment]
Did you regenerates the dist folder ? Maybe juste send the src folder and remove the `npm run build` task ? Because when I run it with the npm package, it fails, but when I run it from sources `node src/cli.js` it's good.

**Comment by mcchatman8009** [comment]
Sorry, try running install it globally again. I just push out version 1.0.12

**Comment by mcchatman8009** [comment]
Thanks again @scorsi
