### ISSUE TITLE
Fails with cannot find module 'anltr4/index' with antlr4 4.9

### ISSUE THREAD

**Issue by dmaffitt** [mcchatman8009/antlr4-tool#35]
All is well with antlr4 4.8.0 but updating to 4.9 causes the following.  I'm brand new in the javascript world so not very effective in debugging this. It seems there was an issue like this in 2018 https://github.com/mcchatman8009/antlr4-tool/issues/14. The only change I made was bumping antlr4 from 4.8 to 4.9.

yarn run v1.19.2
$ antlr4-tool --output-dir src/parser --language typescript grammar/DE6Parser.g4 grammar/DE6Lexer.g4 grammar/TagPath.g4
Compiling grammar/DE6Parser.g4, grammar/DE6Lexer.g4, grammar/TagPath.g4...
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'antlr4/index'
Require stack:
- /Users/drm/projects/nrg/dicomeditjs/de6js/node_modules/antlr4-tool/dist/antlr-core/parser-util.js
- /Users/drm/projects/nrg/dicomeditjs/de6js/node_modules/antlr4-tool/dist/antlr-core/antlr-compiler.js
- /Users/drm/projects/nrg/dicomeditjs/de6js/node_modules/antlr4-tool/dist/antlr-core/index.js
- /Users/drm/projects/nrg/dicomeditjs/de6js/node_modules/antlr4-tool/dist/compile.js
- /Users/drm/projects/nrg/dicomeditjs/de6js/node_modules/antlr4-tool/dist/cli.js
- /Users/drm/projects/nrg/dicomeditjs/de6js/node_modules/antlr4-tool/dist/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at vmRequire (/Users/drm/projects/nrg/dicomeditjs/de6js/node_modules/antlr4-tool/dist/antlr-core/parser-util.js:24:32)
    at evalmachine.<anonymous>:3:14
    at Script.runInContext (vm.js:142:18)
    at Object.runInContext (vm.js:293:6)
    at Object.readParser (/Users/drm/projects/nrg/dicomeditjs/de6js/node_modules/antlr4-tool/dist/antlr-core/parser-util.js:28:8)
    at AntlrCompiler.compileTypeScript (/Users/drm/projects/nrg/dicomeditjs/de6js/node_modules/antlr4-tool/dist/antlr-core/antlr-compiler.js:66:37)
    at /Users/drm/projects/nrg/dicomeditjs/de6js/node_modules/antlr4-tool/dist/antlr-core/index.js:40:78
    at /Users/drm/projects/nrg/dicomeditjs/de6js/node_modules/antlr4-tool/dist/antlr-core/index.js:17:23 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/drm/projects/nrg/dicomeditjs/de6js/node_modules/antlr4-tool/dist/antlr-core/parser-util.js',
    '/Users/drm/projects/nrg/dicomeditjs/de6js/node_modules/antlr4-tool/dist/antlr-core/antlr-compiler.js',
    '/Users/drm/projects/nrg/dicomeditjs/de6js/node_modules/antlr4-tool/dist/antlr-core/index.js',
    '/Users/drm/projects/nrg/dicomeditjs/de6js/node_modules/antlr4-tool/dist/compile.js',
    '/Users/drm/projects/nrg/dicomeditjs/de6js/node_modules/antlr4-tool/dist/cli.js',
    '/Users/drm/projects/nrg/dicomeditjs/de6js/node_modules/antlr4-tool/dist/app.js'
  ]
}
error Command failed with exit code 1.

**Comment by frankjar** [comment]
hi, doing the same here.

Totally new project with 
- antlr4 4.9.0 with the CSV grammar : trash with the same error
- antlr4 4.8.0 with the CSV grammar : fine !

thanks

**Comment by quantrpeter** [comment]
is it fix?

**Comment by billbarni** [comment]
I have this problem. Can't get around it. No matter how I generate, there are several problems impeding the usage.

**Comment by iosonoagenda** [comment]
Same problem.

- OS: Ubuntu 21.10
- antlr4-tool: 1.1.1
- antlr4: 4.10.0

Any fix?
